CREATE DATABASE KINOKZ
USE KINOKZ

CREATE TABLE AFISHA(
A_CODE VARCHAR(10) PRIMARY KEY,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL)

CREATE TABLE AFISHA_DETAIL(
AD_CODE INT IDENTITY(100,1) PRIMARY KEY,
A_CODE VARCHAR(10) FOREIGN KEY REFERENCES AFISHA(A_CODE) ON DELETE CASCADE,
NAME VARCHAR(100) NOT NULL,
CAST VARCHAR(MAX),
DIRECTOR VARCHAR(35),
PRODUCTION VARCHAR(35),
RESTRICTION VARCHAR(10),
MINUTES INT NOT NULL,
REV_KINOKZ DEC(3,2),
GENRE VARCHAR(20),
DESCRIPTION VARCHAR(MAX),
EVENT_CATEGORY VARCHAR(30),
LANGUAGE VARCHAR(15))

CREATE TABLE AUDITORIUM(
AUD_ID VARCHAR(10) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CAPACITY INT NOT NULL)

CREATE TABLE SCHEDULED_AFISHA(
SA_ID INT IDENTITY(1,1) PRIMARY KEY,
A_CODE VARCHAR(10) FOREIGN KEY REFERENCES AFISHA(A_CODE) ON DELETE CASCADE,
AUD_ID VARCHAR(10) FOREIGN KEY REFERENCES AUDITORIUM(AUD_ID),
SEANS_TIME DATETIME,
PRICE_ADULT INT,
PRICE_STUDENT INT,
PRICE_KID INT )
