CREATE DATABASE LAB_3
USE LAB_3

/*A*/

/*1a*/

SELECT * FROM Students
WHERE DOMAIN = 'Finance'

/*1B*/

SELECT TOP 1 * FROM Students AS A
ORDER BY RANK 

SELECT TOP 1 * FROM Students
ORDER BY RANK DESC


/*2A*/

UPDATE STUDENTS
SET NAME_OF_THE_STUDENT = 'Camila Wood'
WHERE NAME_OF_THE_STUDENT LIKE 'Camila Biden'

SELECT NAME_OF_THE_STUDENT FROM Students
WHERE NAME_OF_THE_STUDENT LIKE 'Camila%'

/*2B*/

SELECT * FROM STUDENTS
ORDER BY SEMESTER DESC

UPDATE STUDENTS
SET SEMESTER = 'Graduated'
WHERE SEMESTER = '9th'


SELECT SEMESTER FROM STUDENTS

/*B*/

/*1B*/

ALTER TABLE STUDENTS
ADD Teacher VARCHAR(70)

UPDATE STUDENTS
SET TEACHER = 'Andrew Tompson'
WHERE DOMAIN = 'BA'


UPDATE STUDENTS
SET TEACHER = 'Ashley Morningstar'
WHERE DOMAIN = 'IB'


UPDATE STUDENTS
SET TEACHER = 'Rokshata Gray'
WHERE DOMAIN = 'DM'

UPDATE STUDENTS
SET TEACHER = 'Nasib Taleb'
WHERE DOMAIN = 'Finance'

UPDATE STUDENTS
SET TEACHER = 'Enthony Hopkins'
WHERE DOMAIN = 'Generic'

UPDATE STUDENTS
SET TEACHER = 'Cristian Bale'
WHERE DOMAIN = 'E&I'

SELECT NAME_OF_THE_STUDENT, Teacher, DOMAIN  FROM Students
WHERE DOMAIN = 'IB'

/*C*/

/*1A*/

SELECT DOMAIN, COUNT(NAME_OF_THE_STUDENT) AS NUMBER_OF_STUDENT FROM Students
GROUP BY DOMAIN

/*1B*/

SELECT DOMAIN, AVG(DOMAIN_SPECIFIC_SCORE_OUT_50) AS SPECIFIC_SCORE FROM Students
GROUP BY DOMAIN

/*2C*/
SELECT NAME_OF_THE_STUDENT, DOMAIN, TOTAL_SCORE_OUT_OF_100 FROM STUDENTS
WHERE TOTAL_SCORE_OUT_of_100 >= (SELECT AVG(TOTAL_SCORE_OUT_OF_100) AS AVG_SCORE FROM STUDENTS)

/*2D*/
SELECT NAME_OF_THE_STUDENT, DOMAIN, PERCENTILE FROM Students
WHERE PERCENTILE >= '0.8'

/*D*/

/*1*/
SELECT NAME_OF_THE_STUDENT, DOMAIN, SEMESTER FROM Students


/*2*/
SELECT DOMAIN , AVG(TOTAL_SCORE_OUT_OF_100) AS AVG_SCORE FROM STUDENTS 
GROUP BY DOMAIN

select * from students 